site_name: mytqwq       # 站点名称，显示于导航栏
site_url: "https://mao1t.github.io/"  # 部署后的域名

nav:                       # 导航栏菜单结构，层级与目录结构对应
  - 首页: index.md
  - 微积分:
       - test: 微积分/qwq.md


theme:
  name: material          # 启用 Material 主题
  features:
    - navigation.tabs      # 顶部标签页导航
    - navigation.sections  # 自动提取标题生成章节锚点
  palette:
    - scheme: default      # 浅色模式
    - scheme: slate        # 暗黑模式（用户可切换）

extra_css:
  - stylesheets/extra.css # 自定义CSS